resources:
  repositories:
  - repository: UDP
    type: github
    endpoint: devopsnights
    name: devopsnights/UDP

trigger:
- master

pool:
  vmImage: ubuntu-latest

# jobs:
# - template: src\build\nodejs-build-jobs.yml@UDP

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: nodejs

  - deployment: 
    environment: development
    strategy:  
      runOnce:
        deploy:
          steps:


            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'nodejs'
                targetPath: '$(Pipeline.Workspace)'
            - powershell: | 
                cd $(Pipeline.Workspace)
                Get-ChildItem -recurse
            - task: AzureWebApp@1
              displayName: 'Azure Web App Deploy: nodejs-cicd'
              inputs:
                azureSubscription: 'UDP-MVP'
                appType: 'webAppLinux'
                appName: 'wa-udp-nodejs'
                package: '$(Pipeline.Workspace)/**/*.zip'
                runtimeStack: 'NODE|12-lts'
                startUpCommand: 'npm run start'
                
            # - task: AzureRmWebAppDeployment@4
            #   inputs:
            #     ConnectionType: 'AzureRM'
            #     azureSubscription: 'UDP-MVP'
            #     appType: 'webAppLinux'
            #     WebAppName: 'wa-udp-nodejs'
            #     packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'