resources:
  repositories:
  - repository: UDP
    type: github
    endpoint: devopsnights
    name: devopsnights/UDP

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- template: src\build\nodejs-build-jobs.yml@UDP

- deployment: 
  strategy:
    runOnce:
      deploy:
        steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'UDP-MVP'
              appType: 'webAppLinux'
              WebAppName: 'wa-udp-nodejs'
              packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'