resources:
  repositories:
  - repository: UDP
    type: github
    endpoint: devopsnights
    name: devopsnights/UDP

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- template: src\build\nodejs-build-jobs.yml@UDP

- deployment: 
  environment: development
  strategy:  
    runOnce:
      deploy:
        steps:

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'UDP-MVP'
              appType: 'webAppLinux'
              WebAppName: 'wa-udp-nodejs'
              packageForLinux: '$(System.ArtifactsDirectory)/**/*.tgz'